### ISSUE TITLE
view problem

### ISSUE THREAD

**Issue by alireza1992** [willharrison/twitter-clone#5]
do i need gulp and stuff?
i get a messy view.. :/

**Comment by alireza1992** [comment]
i got the gulp..
but still having some trouble like it's logged in automatically...
somehow i cant  log out...

**Comment by alireza1992** [comment]
also i cant post anything , here is the error : - bower_components/jquery/dist/jquery.js <-- Not Found

**Comment by alireza1992** [comment]
i have a question , is it with vue.js ??

**Comment by willharrison** [comment]
@alireza1992 
I recently had to move this over to a different server, so I have some steps that might help you:

```
npm install --global gulp
npm install --global bower
npm install
composer install
bower install
gulp
php artisan serve
```

Assuming you have composer, npm, and php (including mcrypt) installed.
